### ISSUE TITLE
Compare function

### ISSUE THREAD

**Issue by floatdrop** [mikolalysenko/uniq#3]
> compare is an optional comparison function that returns 0 when two items are equal, and something non-zero when they are different. If unspecified, then the default equals will be used.

It seem strange, that falsy value represents equality. Is there a reason, that compare function not returning `Boolean`?

**Comment by mikolalysenko** [comment]
Ah, it isn't clear but really compare should be a comparator function as you would pass to array.sort()

**Comment by floatdrop** [comment]
Hm... Make sens, thanks!
